version: '3'
services:
  gitea:
    container_name: gitea
    image: gitea/gitea
    volumes: 
      - /root/data/var/lib/gitea/:/data
    ports:
      - "10022:22"
      - "10080:3000"
  drone-server:
    container_name: drone-server
    image: drone/drone
    environment:
      - DRONE_GITEA_SERVER=https://hub.${ACME_DOMAIN}
      - DRONE_SERVER_HOST=drone.${ACME_DOMAIN}
      - DRONE_SERVER_PROTO=https
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true
      - DRONE_OPEN=true
      # - DRONE_RUNNER_CAPACITY=2 #如果作为多机服务器，注释此行
    volumes: 
      # - /var/run/docker.sock:/var/run/docker.sock #如果作为多机服务器，注释此行
      - ./data/var/lib/drone/:/data
    ports:
      - "10081:80"
      - "10082:443"
  drone-agent:
    container_name: drone-agent
    image: drone/agent
    command: agent
    environment:
      - DRONE_RPC_SERVER=https://drone.${ACME_DOMAIN}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_NAME=local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  docker-registry:
    container_name: registry
    image: registry
    volumes:
      - /root/data/opt/data/registry/:/var/lib/registry
    ports: 
      - "10028:5000"
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - ./config/nginx.conf/:/etc/nginx/
      - ./data/nginxlog/:/var/log/nginx/
      - ${NGINX_SSL_CER}:/cer
      - ${NGINX_SSL_KEY}:/key
    ports: 
      - "80:80"
      - "443:443"